### ISSUE TITLE
Only enable on user optin

### ISSUE THREAD

**Issue by jaschaio** [ThemeAvenue/Remote-Dashboard-Notifications#6]
Hey Guys, awesome idea and really really useful.

Anyway, have you been thinking about this:
https://wordpress.org/support/topic/remote-dashboard-notifications-allowed

It looks like currently the user have no option to optin or optout of this and is therefore not within the wordpress.org guidelines

**Comment by julien731** [comment]
The thing is that the opt-in option should be added by the developer directly. The calls to the server when using the RDN client class are done if and only if the class is instantiated. When integrating it to a plugin / theme, the developer should add an option to enable / disable it and only instantiate the RDN class if the user enabled it.
